<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationIcon>Assets\localization-workbench.ico</ApplicationIcon>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Localization Workbench</AssemblyName>
    <RootNamespace>LocalizationWorkbench</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
    <Version>2.0.0-rc.1</Version>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpCompress" Version="0.50.4" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\localization-workbench.ico"
                      LogicalName="LocalizationWorkbench.Assets.localization-workbench.ico" />
  </ItemGroup>


</Project>
