using LocalizationWorkbench.Models;

namespace LocalizationWorkbench.Localization;

public sealed class Localizer
{
    private readonly Dictionary<string, string> _strings = BuildEnglish();

    public string T(string key)
    {
        if (_strings.TryGetValue(key, out var value) && !string.IsNullOrWhiteSpace(value))
            return value;
        return key;
    }

    public string LanguageName(BuildLanguage language) => T($"language.{language.Key}");

    private static Dictionary<string, string> BuildEnglish() => new(StringComparer.OrdinalIgnoreCase)
    {
        ["app.title"] = AppConstants.AppName,
        ["ui.build_language"] = "Build languages",
        ["ui.extract"] = "EXTRACT",
        ["ui.build_modular"] = "BUILD MODULAR",
        ["ui.build_all_in_one"] = "BUILD ALL-IN-ONE",
        ["ui.tab_game"] = "GAME",
        ["ui.tab_mods"] = "MODS",
        ["ui.scan_game"] = "SCAN GAME",
        ["ui.scan_mods"] = "SCAN MODS",
        ["ui.extract_game"] = "EXTRACT",
        ["ui.build_game"] = "BUILD",
        ["ui.scanning_game"] = "Scanning base game...",
        ["ui.extracting_game"] = "Extracting all game languages...",
        ["ui.building_game"] = "Building game localization package...",
        ["ui.available"] = "Available",
        ["ui.game_paths_missing"] = "Set the game Paks folder and verify the bundled tools before scanning the base game.",
        ["ui.settings"] = "Settings",
        ["ui.open_jsons_folder"] = "Open JSONs",
        ["ui.open_output"] = "Open output",
        ["ui.log"] = "Log",
        ["ui.mod"] = "Mod",
        ["ui.localization_types"] = "Localization",
        ["ui.status"] = "Status",
        ["ui.details"] = "Details",
        ["ui.scanning"] = "Scanning mods...",
        ["ui.extracting"] = "Extracting localization...",
        ["ui.building"] = "Building localization packages...",
        ["ui.idle"] = "Idle",
        ["ui.done"] = "Done",
        ["ui.cancel"] = "Cancel",
        ["ui.save"] = "Save",
        ["ui.browse"] = "Browse...",
        ["ui.paths"] = "Folders",
        ["ui.tools"] = "Tools",
        ["ui.game_paks"] = "Game Paks folder",
        ["ui.mods_folder"] = "Mods folder",
        ["ui.source_folder"] = "Source folder",
        ["ui.translations_folder"] = "Translations folder",
        ["ui.output_folder"] = "Output folder",
        ["ui.reset_workspace_paths"] = "Reset workspace paths",
        ["ui.retoc"] = "retoc.exe",
        ["ui.uassetgui"] = "UAssetGUI.exe",
        ["ui.mappings"] = "Mappings.usmap",
        ["ui.repak"] = "repak.exe",
        ["ui.s2hocmm"] = "S2HOCMM.exe",
        ["ui.auto_scan"] = "Scan automatically when folders change",
        ["ui.no_translations"] = "No translation JSONs were found.",
        ["ui.no_extract"] = "There is no new or changed localization to extract.",
        ["ui.no_languages_selected"] = "Select at least one build language.",
        ["ui.operation_failed"] = "Operation failed",
        ["ui.operation_complete"] = "Operation complete",
        ["ui.build_complete"] = "Build finished.",
        ["ui.build_summary_output"] = "Output: {0}",
        ["ui.delete_source_data"] = "DELETE SOURCE DATA",
        ["ui.delete_source_confirm"] = "Delete all GAME and MODS source data?\r\n\r\n{0}\r\n\r\nTranslations and Output will not be changed.",
        ["ui.source_deleted"] = "GAME and MODS source data deleted. Extraction will be required again.",
        ["ui.source_empty"] = "There is no source data to delete.",
        ["ui.source_path_missing"] = "Source folder is not configured.",
        ["ui.source_delete_failed"] = "Could not delete source data:\r\n{0}",
        ["ui.select_folder"] = "Select folder",
        ["status.no_localization"] = "No supported localization",
        ["status.needs_extraction"] = "Needs extraction",
        ["status.missing_translation"] = "Missing translation",
        ["status.available"] = "Available",
        ["status.extracted"] = "Extracted",
        ["status.built_verified"] = "Built & verified",
        ["status.no_language_selected"] = "No build language selected",
        ["status.error"] = "Error",
        ["help.status.no_localization"] = "This mod does not contain localization data supported by this tool, so nothing needs to be extracted from it.",
        ["help.status.needs_extraction"] = "This mod is new or has been updated. Extract it before building a translation.",
        ["help.status.missing_translation"] = "The mod was extracted successfully, but no finished translation was found in the Translations folder.",
        ["help.status.available"] = "The mod is extracted, up to date, and a matching translation is available. It can be built now.",
        ["help.status.extracted"] = "The mod localization has been extracted and its translation JSON is ready to build.",
        ["help.status.built_verified"] = "The finished package was built and checked successfully.",
        ["help.status.no_language_selected"] = "Check at least one build language. Extraction remains available, but building is disabled.",
        ["language.arabic"] = "Arabic",
        ["language.chinese_simplified"] = "Chinese (Simplified)",
        ["language.chinese_traditional"] = "Chinese (Traditional)",
        ["language.czech"] = "Czech",
        ["language.english"] = "English",
        ["language.french"] = "French",
        ["language.german"] = "German",
        ["language.italian"] = "Italian",
        ["language.japanese"] = "Japanese",
        ["language.korean"] = "Korean",
        ["language.polish"] = "Polish",
        ["language.portuguese_brazil"] = "Portuguese (Brazil)",
        ["language.russian"] = "Russian",
        ["language.serbian"] = "Serbian",
        ["language.spanish_europe"] = "Spanish (Europe)",
        ["language.spanish_latin_america"] = "Spanish (Latin America)",
        ["language.turkish"] = "Turkish",
        ["language.ukrainian"] = "Ukrainian",
    };
}
